# Generated by Django 4.2 on 2025-12-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aira_app", "0003_alter_detailimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STATIONERY", "Stationery"),
                            ("ELECTRONICS", "Electronics"),
                            ("LAB", "Lab Equipment"),
                            ("FURNITURE", "Furniture"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Lab/room/store location (optional)",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
