# Generated by Django 4.2 on 2025-12-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aira_app", "0004_inventoryitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacementSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_offers", models.PositiveIntegerField(default=0)),
                ("highest_package", models.CharField(max_length=50)),
                ("average_package", models.CharField(max_length=50)),
                ("top_recruiters", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
