# Generated by Django 4.2 on 2025-12-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aira_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ANNOUNCEMENT", "Announcement"),
                            ("PLACEMENT", "Placement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="details/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
