# Generated by Django 4.2 on 2025-12-10 04:22

import aira_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aira_app", "0002_detailimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailimage",
            name="image",
            field=models.ImageField(upload_to=aira_app.models.detail_image_upload_path),
        ),
    ]
